export * from "./Main";
export * from "./NotFound";
export * from "./Dashboard";
export * from "./Login";
export * from "./Logout";
export * from "./SignIn";
export * from "./Analytics";
// export * from "./KnowledgeBase";
export { default as KnowledgeBase } from './KnowledgeBase/KnowBase';
export { default as KnowledgeBaseUser } from './KnowledgeBase/KnowBaseUser';
